language: node_js
node_js:
  - 5
  - 6
cache:
  yarn: true
  directories:
    - $HOME/.npm
    - travis_phantomjs
env:
  # Test everything in Webpack 1 and 2
  - export WEBPACK_VERSION="2.1.0-beta.25"
  - export WEBPACK_VERSION="1"
script:
  # Run tests
  - |
    yarn run lint
    echo "TRAVIS_NODE_VERSION=$TRAVIS_NODE_VERSION"
    if [ "$TRAVIS_NODE_VERSION" == "5" ]; then
      NODE_ENV=test node --harmony-proxies $(npm bin)/jest
    else
      yarn run test:jest
    fi
  # Build all examples
  - yarn run build
  - yarn run build:customised
  - yarn run build:sections
  # Check that examples really works: no JS errors on load
  - yarn run phantomjs
  - yarn run phantomjs:customised
  - yarn run phantomjs:sections
  # Manually install Webpack 1 or 2
  - 'if [ "$WEBPACK_VERSION" ]; then yarn add webpack@^$WEBPACK_VERSION; fi'
before_install:
  # Upgrade PhantomJS
  - |
      export PHANTOMJS_VERSION=2.1.1
      export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH
      if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then
        rm -rf $PWD/travis_phantomjs
        mkdir -p $PWD/travis_phantomjs
        wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2
        tar -xvf phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs
      fi
      phantomjs -v
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
